name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '31 1,12 * * *'

jobs:
  ubuntu:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout V
        uses: actions/checkout@v2
        with:
          repository: vlang/v
      - name: Checkout c2v
        uses: actions/checkout@v2
        with:
          path: c2v

      - name: Build V
        run: make && ./v symlink -githubci

      - name: Build c2v and setup ~/code
        run: |
          ls -la /home/runner/work/c2v/c2v/c2v
          ln -s  /home/runner/work/c2v/c2v/c2v ~/.vmodules/c2v
          mkdir -p ~/code/
          v ~/.vmodules/c2v/
          ~/.vmodules/c2v/c2v || true

      - name: Test c2v
        run: |
          v test ~/.vmodules/c2v/
          v run ~/.vmodules/c2v/tests/run_tests.vsh

      - name: Build original Chocolate Doom
        run: |
          git clone --quiet --depth 1 https://github.com/vlang/doom ~/code/doom
          cd ~/code/doom
          cmake -DCMAKE_BUILD_TYPE=Debug .
          make chocolate-doom

      - name: Translate p_enemy.v
        run: |
          cd ~/.vmodules/c2v/
          v run tools/build_doom_file.vsh doom/p_enemy
