name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '31 1,12 * * *'

jobs:
  ubuntu:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout V
        uses: actions/checkout@v2
        with:
          repository: vlang/v
      - name: Checkout c2v
        uses: actions/checkout@v2
        with:
          path: /home/runner/.vmodules/c2v

      - name: Build V
        run: make && sudo ./v symlink

      - name: Build c2v
        run: |
          ls -lart ~/.vmodules/
          ls -lart ~/.vmodules/c2v/
          v ~/.vmodules/c2v/
          ~/.vmodules/c2v/c2v

      - name: Test c2v
        run: |
          v test ~/.vmodules/c2v/
          v run ~/.vmodules/c2v/tests/run_tests.vsh

      - name: Translate p_enemy.v
        run: |
          pwd
          mkdir -p ~/code/
          git clone --quiet --depth 1 https://github.com/vlang/doom ~/code/doom
          cd ~/.vmodules/c2v/
          v run tools/build_doom_file.vsh doom/p_enemy

  macos:
    runs-on: macos-10.15
    steps:
      - name: Checkout V
        uses: actions/checkout@v2
        with:
          repository: vlang/v
      - name: Checkout c2v
        uses: actions/checkout@v2
        with:
          path: /home/runner/.vmodules/c2v

      - name: Build V
        run: make && sudo ./v symlink

      - name: Build c2v
        run: |
          ls -lart ~/.vmodules/
          ls -lart ~/.vmodules/c2v/
          v ~/.vmodules/c2v/
          ~/.vmodules/c2v/c2v

      - name: Test c2v
        run: |
          v test ~/.vmodules/c2v/
          v run ~/.vmodules/c2v/tests/run_tests.vsh

      - name: Translate p_enemy.v
        run: |
          pwd
          mkdir -p ~/code/
          git clone --quiet --depth 1 https://github.com/vlang/doom ~/code/doom
          cd ~/.vmodules/c2v/
          v run tools/build_doom_file.vsh doom/p_enemy
